#! /bin/bash

set -eo pipefail

. ~/.bash_aliases
shopt -s expand_aliases

ciao

#
# download data
#

. src/functions.bash

mkdir -p data
cd data
for o in $(obsids)
do
  files=evt1,bpix,pbk,msk,flt,asol,bias,stat,mtl
  instrument $o | grep -qi hrc && files=evt1,bpix,msk,flt,asol,dtf,mtl
  download_chandra_obsid $o $files
done
cd -

