#! /bin/bash

set -eo pipefail

. ~/.bash_aliases
shopt -s expand_aliases nocasematch

ciao

. src/functions.bash

tgreprocess=/data/legs/rpete/flight/analysis_functions/tg_reprocess

# whether to force reprocessing if tg_reprocess outdir already exists
force=0

for o in $(obsids)
do
    [ -f data/$o/tg_reprocess/*_evt2.fits -a $force -eq 0 ] && continue

    badpix=''
    [[ $(instrument $o) =~ hrc ]] && badpix='--badpix CALDB'

    perl $tgreprocess $badpix data/$o 2>&1 | tee data/$o/tg_reprocess.log

    [ $o -eq 5168 ] && {
        /bin/bash ./src/fix_5168
    }

    rm -f data/$o/tg_reprocess/*_evt1{a,}.fits
done
