#! /bin/bash

set -eo pipefail

outdir_top=./srcflux

iqe="$1"
shift
iqe_suffix="$1"
shift
obsids="$@"

<<'COMMENT'
iqe=17
iqe_suffix=_full
obsids='20656 21814 22803 24584 24982 25635 28458 29607'
obsids=31395
time parallel -j 16 /bin/bash 0READMEs/07_README_srcflux $iqe $iqe_suffix ::: $obsids
COMMENT

. ~/.bash_aliases
shopt -s expand_aliases

ciao

. /data/legs/rpete/flight/analysis_functions/caldb_files.bash
. /data/legs/rpete/flight/analysis_functions/tmppdir.bash
. src/functions.bash

iqe_version=N00${iqe}
iqe_dir=/data/legs/rpete/flight/hrci_qe/${iqe_version}/qe${iqe_suffix}

qeu=22
qeu_version=N00${qeu}
qeu_dir=/data/legs/rpete/flight/hrcs_qeu/ARD/v${qeu}/qeu

qe=17
qe_version=N00${qe}
qe_dir=/data/legs/rpete/flight/hrcs_qe/${qe_version}/qe

declare -A i pars
pars=(
    [plerion]='tbabs.nh=3.2;pl.phoindex=1.8'
    [halo]='tbabs.nh=2.4;pl.phoindex=2.1'
)

force=0

for o in $obsids
do
    inst=$(instrument $o)

    bkgreg=./region/bg_i.reg
    echo $inst | \grep -qi hrc-s && bkgreg=./region/${o}_bg.reg

    evt2=$(\ls ./data/$o/tg_reprocess/*evt2.fits*)
    asolfile=$(\ls ./data/$o/primary/pcad*)
    mskfile=$(\ls ./data/$o/secondary/*msk1*)
    bpixfile=$(\ls ./data/$o/tg_reprocess/*bpix*)
    dtffile=$(\ls ./data/$o/primary/*dtf*)

    echo $inst | \grep -qi hrc-i && {
        outdir="${outdir_top}"/i_qe_${iqe_version}${iqe_suffix}
        qe_file=$(match_caldb_file "$evt2" qe "$iqe_dir" "$iqe_version")
        pset ardlib AXAF_HRC-I_QE_FILE="$qe_file"
    }

    echo $inst | \grep -qi hrc-s && {
        outdir="${outdir_top}"/qe_${qe_version}_qeu_${qeu_version}

        punlearn ardlib

        qe_file=$(match_caldb_file "$evt2" qe "$qe_dir" "$qe_version")
        pset ardlib AXAF_HRC-S1_QE_FILE="$qe_file"'[AXAF_QE1]'
        pset ardlib AXAF_HRC-S2_QE_FILE="$qe_file"'[AXAF_QE2]'
        pset ardlib AXAF_HRC-S3_QE_FILE="$qe_file"'[AXAF_QE3]'

        qeu_file=$(match_caldb_file "$evt2" qeu "$qeu_dir" "$qeu_version")
        pset ardlib AXAF_HRC-S1_QEU_FILE="$qeu_file"'[AXAF_QEU1]'
        pset ardlib AXAF_HRC-S2_QEU_FILE="$qeu_file"'[AXAF_QEU2]'
        pset ardlib AXAF_HRC-S3_QEU_FILE="$qeu_file"'[AXAF_QEU3]'
    }

    mkdir -p $outdir

    for type in plerion #halo
    do
        [ $force -eq 0 -a -f $outdir/${o}_${type}_wide.flux ] && continue

        pos='18:33:33.612 -10:34:07.69'
        srcreg=./region/$type.reg

	# source position is off for obsid 5168
        [ -f ./region/${o}_${type}.reg ] &&  {
            pos='18:33:32.429,-10:33:58.95'
            srcreg=./region/${o}_${type}.reg
        }
        punlearn srcflux
        srcflux \
          infile=./data/$o/tg_reprocess/*evt2.fits \
          pos="$pos" \
          outroot=$outdir/${o}_${type} \
          band=wide \
          srcreg=$srcreg \
          bkgreg=$bkgreg \
          psfmethod=ideal \
          model="xstbabs.tbabs*xspowerlaw.pl" \
          paramvals=${pars[$type]} \
          abund=wilm \
          asolfile=$asolfile \
          mskfile=$mskfile \
          bpixfile=$bpixfile \
          dtffile=$dtffile \
          clobber+

        gzip -f $outdir/${o}_${type}_*.{img,expmap}
    done

    punlearn ardlib
done
