#! /bin/bash

. ~/python3_venv/bin/activate

false && {
    outdir=./plots
    mkdir -p $outdir

    python3 src/g21.5_plot_fluxes.py \
	    -o $outdir/g21.5-0.9_hrc_lc.pdf
}

#python3 src/g21.5_plot_fluxes.py -v \
  #-o $outdir/g21.5-0.9_hrc_lc_vlk.pdf

caldbs='qe_N0015_qeu_N0013'

false && {
    for caldb in $caldbs
    do
        outdir=./plots/$caldb
        mkdir -p $outdir
        python3 src/plot_fluxes.py \
          -g './srcflux/i/*.flux' "./srcflux/$caldb/*.flux" \
          -o $outdir/g21.5-0.9_hrc_lc.pdf
    done
}

true && {
    outdir=./plots/i_qe_N0015
    mkdir -p $outdir
    for i in 00 01 15 10 20 25 30 35 def
    do
	isuffix=.$i
	python3 ./src/g21.5_plot_fluxes.py --isuffix="$isuffix" \
	     -o $outdir/g21.5-0.9_hrc_lc${isuffix}.pdf
    done
}
